name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Building...'
        uses: reuixiy/hugo-deploy@v1
        env:
          DEPLOY_REPO: easytzb/easytzb.github.io
          DEPLOY_BRANCH: build
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          TZ: Asia/Shanghai
